### ISSUE TITLE
varying health state utility value by strategy in PSM

### ISSUE THREAD

**Issue by Hazwang** [hesim-dev/rcea#16]
Hi 

Can we vary the utility value by strategy id too in the psm and include this during PSA?

**Comment by dincerti** [comment]
Hi,

You certainly can. For instance, you could try the following so that utility is systematically lower with strategy 2.

```
utility_tbl <- stateval_tbl(
  data.table(strategy_id = c(1, 1, 2, 2),
             state_id = c(1, 2, 1, 2),
             mean = c(H = 1, S = .8, H = .9, S = .7),
             se = c(0.02, .05, 0.02, .05)
  ),
  dist = "beta",
  hesim_data = hesim_dat)
```

**Comment by Hazwang** [comment]
Thank you for your response. Based on Hesim current setup, would it allow for different survival model to be fitted (both PFS and OS) individually across different strategies? For instance, the OS of strategy 1 is fitted with the Weibull model while in strategy 2 the OS is fitted with the log-logistic model. How can I achieve this and stored it in `hesim::flexsurvreg_list`?

**Comment by dincerti** [comment]
Currently a single parametric distribution needs to be specified for each survival model, so this is currently not possible. You can, however, put covariates on multiple parameters of a survival distribution. For example, if a treatment covariate could impact both the shape and scale of the Weibull distribution. By impacting the shape parameter, the hazard could, e.g., be increasing for one treatment and decreasing for another.  Moreover, if this is insufficient, you can approximate very flexible survival curves with splines. 

A [blog post ](https://devinincerti.com/2019/06/18/parametric_survival.html)I wrote a while back may be helpful.

**Comment by Hazwang** [comment]
Hi again,

Firstly, there are no words that can describe how excited I am with hesim. Thank you very much. I have been practising modelling in hesim (and very beginner in R) for quite some time now, however, I could not figure out how to include grp_id option in hesim_data()  and also make the utility for each group systemically differ for an instance. I have tried the following but with no success. Is it possible to populate this in hesim?

strategies <- data.frame(strategy_id = c(1, 2),
                         strategy_name = c("SOC", "TRT"))

patients <- data.table(patient_id = c(1, 2),
                       patient_wt = c(15, 30), 
                       age = c(5, 12),
                       grp_id = c(1, 2))

groups <- data.table(grp_id = c(1, 2),
                     grp_name = c("Child", "Adult"))

states <- data.table(state_id = seq(1, 3),
                        state_name = c("Stable",
                                       "Preprogression",
                                       "Postprogression"))

hesim_dat <- hesim_data(strategies = strategies,
                        patients = patients,
                        states = states)

print(hesim_dat)

utility_tbl <- stateval_tbl(tbl = data.frame(strategy_id = c(1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2),
                                             state_id = c(1, 1, 2, 2, 3, 3, 1, 1, 2, 2, 3, 3),
                                             grp_id = c(1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2),
                                             est = c(0.64, 0.74, 0.65, 0.75, 0.24, 0.34, 0.65, 0.75, 0.66, 0.76, 0.27, 0.37)),
                            dist = "fixed",
                            hesim_data = hesim_dat)
print(utility_tbl)

**Comment by dincerti** [comment]
Hi and thank you for the kind words. Glad you are finding it useful!

As for your question, you should replace `grp_id` with `patient_id`

```
utility_tbl <- stateval_tbl(tbl = data.frame(strategy_id = c(1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2),
                                             state_id = c(1, 1, 2, 2, 3, 3, 1, 1, 2, 2, 3, 3),
                                             patient_id = c(1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2),
                                             est = c(0.64, 0.74, 0.65, 0.75, 0.24, 0.34, 0.65, 0.75,
                                                     0.66, 0.76, 0.27, 0.37)),
                            dist = "fixed",
                            hesim_data = hesim_dat)
```

If you want to use `grp_id`, then you need to specify `grp_var = "grp_id"` as an argument to  [stateval_tbl()](https://hesim-dev.github.io/hesim/reference/stateval_tbl.html). This is a bit confusing but there is a good reason for it. It allows you to have different groups of patients with the same state values in an individual patient simulation (where there can be 1000's of patients) without those necessarily also being the subgroups of interest.
